server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_machugi?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_woogi
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
